{{- if .Values.ingress.enabled -}}
{{- $fullName := include "nearspark.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "nearspark.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - cors.{{ .Values.global.domain }}
      secretName: cert-cors.{{ .Values.global.domain }}
  rules:
    - host: cors.{{ .Values.global.domain }}
      http:
        paths:
        - path: /nearspark
          pathType: Prefix
          backend:
            service:
              name: nearspark
              port: 
                number: 5000
  {{- end }}
